from django.urls import include, path
from rest_framework import routers
from .views import (
    CustomUserViewSet,
    IngredientViewSet,
    RecipeViewSet,
    TagViewSet,
)

app_name = 'api'

# Create a router for API endpoints
router_v1 = routers.DefaultRouter()

# Register viewsets for different endpoints
router_v1.register('users', CustomUserViewSet, basename='users')
router_v1.register('ingredients', IngredientViewSet, basename='ingredients')
router_v1.register('tags', TagViewSet, basename='tags')
router_v1.register('recipes', RecipeViewSet, basename='recipes')

urlpatterns = [
    # Include the URLs generated by the router for API endpoints
    path('', include(router_v1.urls)),

    # Include the authentication URLs provided by djoser
    path('auth/', include('djoser.urls')),

    # Include the token-based authentication URLs provided by djoser
    path('auth/', include('djoser.urls.authtoken')),
]
