# Generated by Django 4.2.2 on 2023-06-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Guest'), ('author', 'Authorized user'), ('admin', 'Administrator')], default='user', max_length=20, verbose_name='Role'),
        ),
    ]
